name: cansat_interface
description: CANSAT Interface App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.3

dependencies:
  bloc: ^8.1.1
  ditredi: ^1.0.3
  equatable: ^2.0.5
  fluent_ui: ^4.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_libserialport: ^0.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  mqtt_client: ^9.7.4
  shared_preferences: ^2.0.17
  syncfusion_flutter_charts: ^20.4.50
  syncfusion_flutter_core: ^20.4.50
  syncfusion_flutter_gauges: ^20.4.50
  vector_math: ^2.1.4

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  msix: ^3.7.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/models/
  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/RobotoMono-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: Roboto-Thin
      fonts:
        - asset: assets/fonts/RobotoMono-Thin.ttf

flutter_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256
  linux:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256

msix_config:
  display_name: CANSAT Interface
  publisher_display_name: Piero Angelo Morales Alcalde
  identity_name: 29622PieroAngeloMoralesAl.CANSATInterface
  publisher: CN=91BE0923-E8F6-4F62-AE9E-2A123C9AC1AF
  msix_version: 1.2.0.0
  languages: es-es
  logo_path: assets/app_icon.png
  capabilities: internetClient
  store: true
